pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'master',
                        credentialsId: 'b455246d-17de-4bda-8ee7-55a4f4cd5ae5',
                        url: 'https://github.com/paragrajput/webapp-deploy-in-docker.git'
                }
            }
        }
        stage('Docker Deploy') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}
