pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'master',
                        credentialsId: 'b455246d-17de-4bda-8ee7-55a4f4cd5ae5',
                        url: 'https://github.com/paragrajput/webapp-deploy-in-docker.git'
                }
            }
        }
        stage('Checking container is running and stop it') {
            steps {
                sh 'docker ps -f name=react-app-c -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -fname=react-app-c -q | xargs -r docker container rm'
            }
        }
        stage('Docker Deploy') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}
