pipeline {
    agent any

    stages {
        stage('GitHub Checkout') {
            steps {
                git url:'https://github.com/paragrajput/webapp-deploy-in-docker.git'
            }
        }
        stage('Deploy') {    
            //Deploy 
			steps {
				sh 'echo Hello'
			}
		}
    }
}
