pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'master',
                        credentialsId: '< jenkins credential id paste here >',
                        url: 'https://github.com/paragrajput/webapp-deploy-in-docker.git'
                }
            }
        }
        stage('Packege Install and Build ') {
            steps {
                sh 'npm install && npm run build'
            }
        }
        stage('Deploy and Restart Nginx') {
            steps {
                //Before Copy Check write permission on this path '/var/www/html' 
                sh 'cp -r build/* /var/www/html/'
                sh 'sudo systemctl restart nginx.service'
            }
        }
    }
}
