name: Docker Image CI

on:
  push:
    branches: [ "githubaction" ]
  pull_request:
    branches: [ "githubaction" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: demo # Define the image name
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production] # Define your environments
    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME}}:latest

    # Push the Docker image
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME}}:latest
