name: Docker Image CI

on:
  push:
    branches: [ "githubaction" ]
  pull_request:
    branches: [ "githubaction" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:latest

    # Push the Docker image
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest
